### ISSUE TITLE
Running multiple commands sequentially (&&) in a script , files/folders created by the 1st command are not available to the 2nd one

### ISSUE THREAD

**Issue by davidesalerno** [bitrise-steplib/steps-npm#50]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES (On Windows I cannot test using BitRise CLI)

### Issue description

Running multiple commands sequentially in a script is not working as expected because the 2nd command executed it is not able to find a folder created by the first one
### Bitrise info

- Build URL: https://app.bitrise.io/build/6a6c895b-4a93-4bc5-9ba4-90753542319f
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO (but we could do it)
- Log: Error: Path '/Users/vagrant/git/pacts' given in pactFilesOrDirs does not exists.

<details>
  <pre>
 [2021-09-14 10:29:57.260 +0000] INFO (2692 on vm-osx-xcode-12.5.x-elite-cb91ecfc-1a97-4582-acea-e2273199daac.local): pact-node@10.13.7: Publishing Pacts to Broker
/Users/vagrant/git/node_modules/@pact-foundation/pact-node/src/publisher.js:36
throw new Error("Path '" + v + "' given in pactFilesOrDirs does not exists.");
^
 
Error: Path '/Users/vagrant/git/pacts' given in pactFilesOrDirs does not exists.
at /Users/vagrant/git/node_modules/@pact-foundation/pact-node/src/publisher.js:36:27
at Array.map (<anonymous>)
at new Publisher (/Users/vagrant/git/node_modules/@pact-foundation/pact-node/src/publisher.js:33:63)
at Object.default (/Users/vagrant/git/node_modules/@pact-foundation/pact-node/src/publisher.js:86:48)
at Pact.publishPacts (/Users/vagrant/git/node_modules/@pact-foundation/pact-node/src/pact.js:110:35)
at Object.<anonymous> (/Users/vagrant/git/pact.publish.js:12:4)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47
  </pre>
</details>

### Steps to reproduce

1. We have got a Single Page Application (SPA) using AngularJS and Capacitor that contains in the tests PactJS for contract testing.
2. We are running the pact tests with all the other unit test of our SPA using Jest
3. After tests are successfully executed we would like to upload the contacts produced by PactJS to our Pact Broker using a node script like suggested here: https://github.com/pact-foundation/pact-js#publish-in-a-custom-script
4. The test execution and the upload on the pact broker are executed in the same npm (test:ci) script and the 2 commands are executed sequentially with the && ("test:ci": "npm run test && node pact.publish"`)
5. If we run the "test:ci" script locally everything works fine and the /pacts/ folder is being created with the contracts tests JSON file. On BitRise when the node script it is executed it seems not to be able to find the /pacts/ folder

**Comment by davidesalerno** [comment]
The root cause of the issue it is related to the fact that we weren't able to detect when jest-pact mock server had started and so sometimes consumer driver contact test were fired even if the jest-pact mock server wasn't up and running causing the tests and this test to fail even if the file in the ./pacts folder was created.
